### ISSUE TITLE
Looking new maintainer(s)

### ISSUE THREAD

**Issue by pbuyle** [devops-coop/ansible-haproxy#53]
Our company is not using this role anymore and cannot commit to maintaining it. We are looking for an individual or organization that would take over the maintenance.

**Comment by SydOps** [comment]
@pbuyle 

Thanks to ping me for this this. I'd like to apply, but what jobs do I need do if I join?

For example, to implement some changes simpler, I prefer the way described in #44. Will it be merged after I am one of the maintainers?

**Comment by benwebber** [comment]
Thanks for looping me in. I'm interested in maintaining this project as well. My [Minecraft role](https://github.com/benwebber/ansible-minecraft) is a good example of my work.

> We are looking for an individual or organization that would take over the maintenance.

How do you foresee this working? Would you add individual collaborators to this project, or would you consider transferring it to a new organization? Would Floe stay on in an advisory capacity?

---

> For example, to implement some changes simpler, I prefer the way described in #44. Will it be merged after I am one of the maintainers?

Bill, constructs like these are usually a good idea in my opinion. They help satisfy edge cases without having to adjust the template very frequently.

**Comment by pbuyle** [comment]
To clarify, we are not looking for co-maintainers. We are looking for a new maintainer to take over the project. We would transfert ownership of the project to the maintainer or to the organisation of their choice. Once this is done, the maintainer(s) will be in charge of the project and could organize as they see fit. Decisions on pull request, adding more maintainers, project direction, etc. will be theirs to make.

If you are also interested in working together on this, I suggest you discuss which one of you should be _lead_ and get the project transferred to. Once this is done, he would grant the required access for co-maintenance to the other.

**Comment by r-daneel** [comment]
I'm willing to participate and host the repo if needed.
I went through some other haproxy roles and found most of them less mature.
Also some in ansible galaxy are direct copies of this repo.

**Comment by pbuyle** [comment]
@SydOps @benwebber @r-daneel I added all three of you as collaborator of the project, with write access. Please choose who I should transfer the porject too (another option is to create a Organization for the project, but that seems overkill).

**Comment by benwebber** [comment]
Thanks @pbuyle!

I think this project should be attached to an organization and not an individual if we share maintainership. Maybe we can transfer other roles there in the future.

I've created the @devops-coop (DevOps Co-op) organization and added @SydOps, @r-daneel, and myself. Does that work for you folks?

**Comment by pbuyle** [comment]
@benwebber That works for me, but I can transfert the repo to the org unless I'm admin there (just tried).

**Comment by benwebber** [comment]
I guess that makes sense. I've made you an owner temporarily, can you try now?

**Comment by pbuyle** [comment]
Project has been transfered

**Comment by benwebber** [comment]
Thanks kindly!
