### ISSUE TITLE
Role is not idempotent

### ISSUE THREAD

**Issue by onitake** [devops-coop/ansible-haproxy#68]
While check mode works as expected and displays a proper diff between old and new configs, executing the role will always rewrite the configuration directories.

This does not actually break things, but seems like poor design.

Is there a particular reason why there is a removal task before writing the configuration files?

If there is concern about leftovers, why not just leave out those that will be written?

Also, it would be better to use the file module instead of running find, I think.

**Comment by benwebber** [comment]
The directories are emptied first so that `assemble` does not collect additional files.

This part of the code is quite old and will probably be replaced very shortly with a simpler template.

**Comment by onitake** [comment]
Thanks for the great fix!

It's a bit unfortunate that standard Ansible distributions don't include jmespath (which is required for json_query) by default, but json_query is so useful that it should be a dependency IMHO.

**Comment by benwebber** [comment]
Ah, shoot. My local Ansible distribution includes that dependency, so I didn't notice it.

We can work around this by writing a custom filter plugin (#77). I'll take a stab at that shortly.
