### ISSUE TITLE
sudo shouldn't be used

### ISSUE THREAD

**Issue by onitake** [devops-coop/ansible-haproxy#71]
Ansible warns about the sudo: yes flag in install.yml:
```
[DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and make sure become_method is 'sudo' 
(default).
This feature will be removed in a future release.
```

I think it is safe to assume the haproxy role is run with superuser rights, so it doesn't make much sense to have the flag there.

**Comment by benwebber** [comment]
This is actually a deprecation warning. When Ansible 1.9 added new privilege escalation backends, they changed `sudo` to `become`. We simply need to rename the parameter.

**Comment by benwebber** [comment]
@onitake Sorry for misunderstanding your original point. Yes, the user should set `become` at the playbook level. The role shoudn't elevate permissions itself.

**Comment by onitake** [comment]
Sorry that I wasn't more clear, but thanks anyway! :)
