### ISSUE TITLE
Braking changes in "Remove unmanaged files for the frontends" task

### ISSUE THREAD

**Issue by homelessnessbo** [devops-coop/ansible-haproxy#76]
After that commt: https://github.com/devops-coop/ansible-haproxy/commit/e91947d76dfc6fc830ccf4f614572f247d5430ed I started to get messages: `fatal: [lb1.prometheus.n1.nato]: FAILED! => {"failed": true, "msg": "The conditional check '(item.path | basename) not in (haproxy_frontends | json_query('[*].name') | map('regex_replace',  '(.*)', '\\\\1.cfg') | list)' failed. The error was: You need to install \"jmespath\" prior to running json_query filter\n\nThe error appears to have been in '/builds/continuous-delivery/prometheus-ansible-deploy/roles/FloeDesignTechnologies.haproxy/tasks/configure.yml': line 17, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: \"Remove unmanaged files for the frontends\"\n  ^ here\n"}`

Using docker from alpine v3.4 with installing pythin with `apk --update add python py-pip`. 
I know that I need just to install some python lib to fix it, but couldnt u add tag before that commit so I could checkout version I need in more human-readable way? (without commit hash, v1.1 like or smthing)

**Comment by homelessnessbo** [comment]
(sorry for initial name and desc, it was just missclick)

**Comment by benwebber** [comment]
Sorry for the unexpected change!

You can point your requirements file to `v1.1.0`, which excludes the `json_query` change. This will be the last full release in the 1.x series as we start working on #54 in earnest.
